task :load_application do
  require 'fx_rates_provider'
end

namespace :fx_feed do
  desc 'Updates the FX Feed with rates not yet saved'
  task :update! => :load_application do
    FXRatesProvider::FXProvider.new.update!
  end
end
